### ISSUE TITLE
Unnecessary check of pixels?

### ISSUE THREAD

**Issue by fenderil** [Coobaha/postcss-variables-loader#1]
`lib/utils.js, string 75`
`result[key] = value.endsWith('px') ? parseInt(value, 10) : value;`

You would get next transform:
`String: '4px 4px' -> Number: 4`
Btw why did you add this check?

**Comment by Coobaha** [comment]
@fenderil Good catch, Thanks! 

This was added so we don't need to always strip px to do the calculations in JS (Common use case is spacing variables)
