### ISSUE TITLE
kebab-case or camelCase

### ISSUE THREAD

**Issue by fenderil** [Coobaha/postcss-variables-loader#2]
Maybe it would be better to get vars in camelCase in JS imports insteed of default css kebab-case?

**Comment by Coobaha** [comment]
Agree! We just use camelCase in CSS too because it is less magic & grepable.

Thanks for the idea @fenderil 

P.S. Maybe it should be optional... Ping me if someone thinks that this behaviour should be switchable or create PR :)

**Comment by Coobaha** [comment]
problem with `lodash/camelCase` is that it converts `color-RGBA` to `colorRgba`. I have changed this behaviour in 629c906, so it converts to `colorRGBA`.

**Comment by fenderil** [comment]
Nice note about RGBA abbreviation. That is what i wanted to use.
