### ISSUE TITLE
Compiled code isn't valid ES5

### ISSUE THREAD

**Issue by tremby** [Coobaha/postcss-variables-loader#4]
I'm not sure if this is intended, and I'm supposed to work around it myself, or if it's a bug.

My project builds with Webpack and Babel, and I'm using the env plugin for Babel, which is configured to target IE11 among others.

But part of postcss-variables-loader is coming out like this:

```js
if (typeof Proxy !== 'undefined') {
    config = new Proxy(config, {
        get(target, key) {
            if (key !== '__esModule' && !target[key]) {
                console.error(`No variable found, check variable key: ["${key.toString()}"]`);
            }
    
            return target[key];
        },
        
        set(target, key) {
            throw new Error('Config variables are immutable ' + key);
        }
    });
}
```

IE11 is choking on the bare "get" and "set" functions in here, since no keys are specified.

I guess this file isn't being transformed. I haven't explicitly told Babel to ignore node_modules, but I'm not sure what its default behaviour is.

If this is expected and something I have to work around, might you be able to point me in the right direction?

**Comment by tremby** [comment]
I was incorrect, sort of...

As I said, I wasn't explicitly excluding `node_modules`, but I do have an `include` rule set to just my `src` directory, which if I understand it correctly acts as a whitelist, so `node_modules` was excluded.

But I've now added `node_modules/postcss-variables-loader` to the `include` list, so it should be processed, but it still comes out the same way.

I noticed that in the file NPM has downloaded for me, `node_modules/postcss-variables/loader/lib/utils.js` line 45 this code is actually in a string. This explains why Babel isn't processing it, I think. But I don't know what to do about it.

**Comment by Coobaha** [comment]
Hi, thanks for report!

Could you please show your webpack loaders config?
You should use babel loader after this plugin, so stringified code will be parsed by babel.
It should look something like `loader: 'babel-loader!postcss-variables-loader'`

**Comment by tremby** [comment]
Oh, that does it!

I had no idea running the output of a non-JS-file loader through Babel was a thing. Now it has all dropped into place -- of course, this loader is returning JS for my app to consume.

For posterity, this was not an issue when building for production. It only affected the build for webpack-dev-server.

Thanks.
