### ISSUE TITLE
Migration to postcss-preset-env maybe?

### ISSUE THREAD

**Issue by ramoona** [Coobaha/postcss-variables-loader#6]
Hi! It looks like your loader is a little bit outdated now because it depends on `postcss-cssnext` which was deprecated some time ago. Do you consider migration to `postcss-preset-env`? Usage of deprecated cssnext causes some problems like an error from browserslist (if you use query like ''not dead", it says that this is an unknown query).

**Comment by Coobaha** [comment]
HI @ramoona! Thanks for raising this problem, I will take a look!

**Comment by Coobaha** [comment]
@ramoona can you please explain what errors do you get? This loader uses cssnext only on JS (side) - it is up to you how to process CSS

**Comment by Coobaha** [comment]
just in case browsers list was added in 5.0.2. Please provide more details about your setup and what errors do you have.

**Comment by ramoona** [comment]
@Coobaha that helped with unknown browser query issue! thanks!
