### ISSUE TITLE
Deprecation warning for parseQuery

### ISSUE THREAD

**Issue by Khrystyna** [Coobaha/postcss-variables-loader#7]
Hi! I see a warning in logs while using the loader: `parseQuery() will be replaced with getOptions() in the next major version of loader-utils.\n    at Object.parseQuery (/Users/khrystynaskvarok/workspace/sting/hob-webshop-platform/frontend/node_modules/postcss-variables-loader/node_modules/loader-utils/index.js:78:3)\n    at Object.exports.default (/Users/khrystynaskvarok/workspace/sting/hob-webshop-platform/frontend/node_modules/postcss-variables-loader/lib/index.js:14:39)`

Here is explained why this warning is thrown [here](https://github.com/webpack/loader-utils/issues/56). Could you please tell if you plan to update the code? :)

**Comment by Coobaha** [comment]
Hi @Khrystyna ! I will check it soon, sorry for the late response

**Comment by Coobaha** [comment]
@Khrystyna please try to use v6.0.0  Warning should be gone :) Also tests are run against webpack v4 and node 12/13 now
